<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authentication' => 'Аутентификация',
    'Login' => 'Войти',
    'Password' => 'Пароль',
    'Please fill out the following fields to login' => 'Пожалуйста, заполните следующие поля для входа в систему',
    'Remember Me' => 'Запомнить меня',
    'Username' => 'Имя пользователя',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
];
