<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'sourcePath' => '@backend',
    'messagePath' => '@backend/messages',
    'languages' => ['ru-RU'],
    'translator' => [
        'Yii::t',
        '\\Yii::t',
    ],
    'sort' => false,
    'removeUnused' => false,
    'only' => ['*.php'],
    'except' => [
        '.svn',
        '.git',
        '/messages',
        '/vendor',
        '/web',
        '/config',
        '/tests',
        '/runtime'
    ],
    'format' => 'php',
    'overwrite' => true,
];
